### ISSUE TITLE
Duplicate repo?

### ISSUE THREAD

**Issue by afdaniele** [duckietown/rpi-docker-python-picamera#1]
Is this a duplicate?

https://github.com/duckietown/rpi-python-picamera

**Comment by breandan** [comment]
Yes, these repositories are duplicates and should be consolidated.

There are currently three outstanding picamera images:

* `duckietown/rpi-docker-python-picamera` (parent repo, pure Python, based on an old Resin image)
  * https://github.com/duckietown/rpi-docker-python-picamera/blob/master18/Dockerfile
  * https://hub.docker.com/r/duckietown/rpi-docker-python-picamera
* `duckietown/rpi-python-picamera` (pure Python, over 50% slimmer, much cleaner)
  * https://github.com/duckietown/rpi-python-picamera/blob/master18/Dockerfile
  * https://hub.docker.com/r/duckietown/rpi-python-picamera
* `duckietown/rpi-duckiebot-ros-picam` (ROS-based, includes all of the [`Software`](https://github.com/duckietown/Software) repository)
  * https://github.com/duckietown/rpi-duckiebot-ros-picam/blob/master18/Dockerfile
  * https://hub.docker.com/r/duckietown/rpi-duckiebot-ros-picam

I recommend we the consolidate the first two into `duckietown/rpi-python-picamera` and keep last one separate. It is not preloaded but it may be useful to have a lightweight camera image. Although `duckietown/rpi-duckiebot-ros-picam` is based on top of `duckietown/rpi-duckiebot-base`, these layers will not be duplicated and this image is currently integrated with the [ROS workflow](http://docs.duckietown.org/DT18/opmanual_duckiebot/out/read_camera_data.html).

cc: @AndreaCensi

**Comment by breandan** [comment]
After validating it works on the Duckiebot, and [updating the Duckiebook](https://github.com/duckietown/docs-opmanual_duckiebot/pull/139) I am hereby archiving this repository in favor of the [new picamera](https://github.com/duckietown/rpi-python-picamera). Long live `duckietown/rpi-python-picamera`.
